name: clean_tdd_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-94.0.dev <4.0.0"

dependencies:
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^8.0.2
  go_router: ^14.6.1
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
